name: Build AegisRDP

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install libxml2
      run: |
        .\vcpkg\vcpkg install libxml2:x64-windows

    - name: Compile
      run: |
        cl src\main.c ^
          /I vcpkg\installed\x64-windows\include ^
          /link ^
          /LIBPATH:vcpkg\installed\x64-windows\lib ^
          libxml2.lib wevtapi.lib

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aegisrdp-build
        path: aegisrdp.exe